import {
  PROFESSIONAL_LAYOUT_TEMPLATE_SCHEMA_VERSION,
  type ProfessionalLayoutNumericDefaults,
  type ProfessionalLayoutPagePolicy,
  type ProfessionalLayoutSupportRule,
  type ProfessionalLayoutTemplateCatalog,
} from './types.js';

const numericDefaults: ProfessionalLayoutNumericDefaults = {
  units: 'mil',
  borderClearance: 100,
  titleBlockMargin: 150,
  componentClearance: 50,
  textClearance: 25,
  sectionClearance: 75,
};

const pagePolicy: ProfessionalLayoutPagePolicy = {
  preferred: 'A4',
  fallback: 'A3',
  allowFallback: true,
  fallbackCondition: 'a4-hard-constraints-unsatisfied',
  requireA4Proof: true,
};

const geometryPolicy = {
  requiredBeforePlacement: true,
  requireRenderedCombinedBounds: true,
  requireTitleBlockBounds: true,
  unavailableBehavior: 'block-placement',
  advisoryOnlyWhenApproximate: true,
} as const;

const baseSupportRules: ProfessionalLayoutSupportRule[] = [
  {
    role: 'decoupling-capacitor',
    parentKinds: ['controller', 'sensor', 'transceiver', 'regulation', 'analog'],
    maximumDistance: 200,
    hard: true,
  },
  {
    role: 'bulk-capacitor',
    parentKinds: ['power-entry', 'regulation'],
    maximumDistance: 350,
    hard: true,
  },
  {
    role: 'crystal-load',
    parentKinds: ['controller', 'clock'],
    maximumDistance: 150,
    hard: true,
  },
  {
    role: 'connector-protection',
    parentKinds: ['connector', 'power-entry', 'interface'],
    maximumDistance: 250,
    hard: true,
  },
  {
    role: 'feedback-network',
    parentKinds: ['regulation', 'analog'],
    maximumDistance: 200,
    hard: true,
  },
  {
    role: 'pull-up-down',
    parentKinds: ['controller', 'sensor', 'interface'],
    maximumDistance: 300,
    hard: false,
  },
];

export const PROFESSIONAL_LAYOUT_TEMPLATE_CATALOG_V1 = {
  schemaVersion: PROFESSIONAL_LAYOUT_TEMPLATE_SCHEMA_VERSION,
  catalogVersion: '1.0.0',
  templates: [
    {
      id: 'usb-powered-mcu-board',
      version: '1.0.0',
      displayName: 'USB-powered MCU board',
      description: 'USB input, protection, regulation, controller, debug, and I/O grouping.',
      signalFlow: 'power-left-signals-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'usb-input', kind: 'power-entry', order: 10, preferredEdge: 'left', notes: 'Place the USB connector at the signal-entry edge.' },
        { id: 'input-protection', kind: 'protection', order: 20, notes: 'Keep protection between connector and downstream circuitry.' },
        { id: 'regulation', kind: 'regulation', order: 30, notes: 'Keep regulator support components inside this block.' },
        { id: 'controller', kind: 'controller', order: 40, preferredEdge: 'center', notes: 'Reserve space on every side for clock, bypass, and fan-out.' },
        { id: 'debug', kind: 'debug', order: 50, notes: 'Keep programming and debug signals near the controller.' },
        { id: 'io-connectors', kind: 'connector', order: 60, preferredEdge: 'right', notes: 'Place user I/O at the output edge.' },
        { id: 'status', kind: 'status-output', order: 70, notes: 'Keep indicators outside critical routing corridors.' },
      ],
      supportRules: baseSupportRules,
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
    {
      id: 'esp32-sensor-node',
      version: '1.0.0',
      displayName: 'ESP32 sensor node',
      description: 'Mixed power, radio MCU, sensor buses, connectors, debug, and status output.',
      signalFlow: 'power-left-signals-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'power', kind: 'power-entry', order: 10, preferredEdge: 'left', notes: 'Keep power entry and protection together.' },
        { id: 'regulation', kind: 'regulation', order: 20, notes: 'Separate noisy conversion from sensor references.' },
        { id: 'radio-controller', kind: 'controller', order: 30, preferredEdge: 'center', notes: 'Reserve antenna and module keep-out space from caller geometry.' },
        { id: 'sensor-bus', kind: 'interface', order: 40, notes: 'Group bus pull-ups with the controller-facing bus.' },
        { id: 'sensors', kind: 'sensor', order: 50, notes: 'Order sensors by shared bus and physical connector relationship.' },
        { id: 'external-connectors', kind: 'connector', order: 60, preferredEdge: 'right', notes: 'Keep exposed interfaces at a page edge.' },
        { id: 'debug', kind: 'debug', order: 70, notes: 'Keep boot and debug support local to the controller.' },
        { id: 'status', kind: 'status-output', order: 80, notes: 'Route status outputs away from sensor inputs.' },
      ],
      supportRules: baseSupportRules,
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
    {
      id: 'battery-powered-iot-node',
      version: '1.0.0',
      displayName: 'Battery-powered IoT node',
      description: 'Battery, charging, protection, regulation, controller, sensing, and radio blocks.',
      signalFlow: 'power-left-signals-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'battery', kind: 'power-entry', order: 10, preferredEdge: 'left', notes: 'Start with the battery and charging boundary.' },
        { id: 'charging-protection', kind: 'protection', order: 20, notes: 'Keep charge and protection parts adjacent to battery entry.' },
        { id: 'regulation', kind: 'regulation', order: 30, notes: 'Separate switched power from sensitive analog sensing.' },
        { id: 'controller-radio', kind: 'controller', order: 40, preferredEdge: 'center', notes: 'Reserve caller-provided antenna keep-outs.' },
        { id: 'sensors', kind: 'sensor', order: 50, notes: 'Group sensors by bus and power domain.' },
        { id: 'interfaces', kind: 'interface', order: 60, notes: 'Keep wake, programming, and external buses distinct.' },
        { id: 'connectors', kind: 'connector', order: 70, preferredEdge: 'right', notes: 'Place exposed connectors at the output edge.' },
        { id: 'status', kind: 'status-output', order: 80, notes: 'Keep indicators from crowding low-power support parts.' },
      ],
      supportRules: baseSupportRules,
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
    {
      id: 'can-rs485-interface',
      version: '1.0.0',
      displayName: 'CAN or RS-485 interface',
      description: 'Field connector, protection, termination, transceiver, optional isolation, and logic.',
      signalFlow: 'left-to-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'field-connector', kind: 'connector', order: 10, preferredEdge: 'left', notes: 'Put the field connector at the entry edge.' },
        { id: 'surge-protection', kind: 'protection', order: 20, notes: 'Place protection immediately behind the field connector.' },
        { id: 'termination-filter', kind: 'support', order: 30, notes: 'Keep termination and common-mode filtering on the bus side.' },
        { id: 'transceiver', kind: 'transceiver', order: 40, preferredEdge: 'center', notes: 'Center the physical-layer transceiver in the signal chain.' },
        { id: 'isolation', kind: 'isolation', order: 50, notes: 'Preserve a visible isolation boundary when requested.' },
        { id: 'logic-interface', kind: 'interface', order: 60, preferredEdge: 'right', notes: 'Keep controller-side signals on the logic side.' },
        { id: 'power', kind: 'regulation', order: 70, notes: 'Group isolated and non-isolated supplies by domain.' },
        { id: 'debug-status', kind: 'debug', order: 80, notes: 'Keep diagnostics out of the field signal corridor.' },
      ],
      supportRules: [
        ...baseSupportRules,
        { role: 'termination', parentKinds: ['transceiver', 'connector'], maximumDistance: 200, hard: true },
        { role: 'connector-filter', parentKinds: ['connector', 'transceiver'], maximumDistance: 250, hard: true },
      ],
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
    {
      id: 'simple-analog-timer',
      version: '1.0.0',
      displayName: 'Simple analog or timer circuit',
      description: 'Input conditioning, timing or analog core, output stage, and local power support.',
      signalFlow: 'left-to-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'input', kind: 'analog', order: 10, preferredEdge: 'left', notes: 'Place the stimulus or signal input first.' },
        { id: 'timing-network', kind: 'timing', order: 20, notes: 'Keep timing and feedback parts adjacent to the core pins.' },
        { id: 'core', kind: 'analog', order: 30, preferredEdge: 'center', notes: 'Center the active analog or timer device.' },
        { id: 'output', kind: 'status-output', order: 40, preferredEdge: 'right', notes: 'Place the load or indication chain to the right.' },
        { id: 'power-support', kind: 'regulation', order: 50, notes: 'Keep bypass and rail symbols close without crossing signal flow.' },
      ],
      supportRules: baseSupportRules,
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
    {
      id: 'medium-mcu-peripheral-board',
      version: '1.0.0',
      displayName: 'Medium-complexity MCU peripheral board',
      description: 'Controller core with clock, memory, mixed peripheral interfaces, connectors, and debug.',
      signalFlow: 'power-left-signals-right',
      numericDefaults,
      pagePolicy,
      geometryPolicy,
      blockOrder: [
        { id: 'power-entry', kind: 'power-entry', order: 10, preferredEdge: 'left', notes: 'Establish power-domain flow before signals.' },
        { id: 'regulation', kind: 'regulation', order: 20, notes: 'Reserve bulk and bypass support space.' },
        { id: 'controller', kind: 'controller', order: 30, preferredEdge: 'center', notes: 'Reserve fan-out corridors around the main controller.' },
        { id: 'clock', kind: 'clock', order: 40, notes: 'Keep the clock loop local to its controller pins.' },
        { id: 'memory', kind: 'memory', order: 50, notes: 'Keep memory and required passives in the controller block.' },
        { id: 'peripherals', kind: 'interface', order: 60, notes: 'Group peripherals by bus and functional relationship.' },
        { id: 'connectors', kind: 'connector', order: 70, preferredEdge: 'right', notes: 'Place external connectors at the page edge.' },
        { id: 'debug', kind: 'debug', order: 80, notes: 'Keep reset, boot, and programming support together.' },
        { id: 'status', kind: 'status-output', order: 90, notes: 'Keep indicators readable and outside dense fan-out.' },
      ],
      supportRules: baseSupportRules,
      hardKeepouts: ['page-border', 'title-block', 'caller-reserved'],
      detachedNetportsAllowed: false,
    },
  ],
} satisfies ProfessionalLayoutTemplateCatalog;
